## SIB - P1

A Jupyter Notebook with examples of how to use the Dataset object.
18/09/2023

In [2]:
from si.data.dataset import Dataset
import numpy as np

# create a dataset
X = np.random.rand(150, 30)
y = np.random.randint(0, 2, 150)
dataset = Dataset(X, y)
dataset.shape()

(150, 30)

In [3]:
# get the X
dataset.X

array([[0.76065875, 0.40786025, 0.03840207, ..., 0.03090158, 0.08059214,
        0.53442546],
       [0.71386972, 0.90644937, 0.31569281, ..., 0.06537296, 0.04965978,
        0.83104544],
       [0.42638116, 0.27103402, 0.74826439, ..., 0.40633314, 0.51073745,
        0.41980396],
       ...,
       [0.79721236, 0.41666262, 0.24975854, ..., 0.03110088, 0.43264085,
        0.04132628],
       [0.97480335, 0.48768445, 0.80232424, ..., 0.35139549, 0.25030268,
        0.35868587],
       [0.4532856 , 0.03343903, 0.48199523, ..., 0.28539468, 0.41314112,
        0.49472407]])

In [4]:
#get the features names
dataset.features

['feat_0',
 'feat_1',
 'feat_2',
 'feat_3',
 'feat_4',
 'feat_5',
 'feat_6',
 'feat_7',
 'feat_8',
 'feat_9',
 'feat_10',
 'feat_11',
 'feat_12',
 'feat_13',
 'feat_14',
 'feat_15',
 'feat_16',
 'feat_17',
 'feat_18',
 'feat_19',
 'feat_20',
 'feat_21',
 'feat_22',
 'feat_23',
 'feat_24',
 'feat_25',
 'feat_26',
 'feat_27',
 'feat_28',
 'feat_29']

In [5]:
# has label?
dataset.has_label()

True

In [6]:
# print the label
dataset.y

array([0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0])

In [7]:
# get classes
dataset.get_classes()

array([0, 1])

In [8]:
# statistics summary
dataset.summary()

feat_0    feat_1    feat_2    feat_3    feat_4    feat_5    feat_6  \
mean    0.517148  0.471276  0.491909  0.540304  0.500128  0.493145  0.456979   
median  0.562291  0.443622  0.500429  0.580741  0.506698  0.500171  0.418293   
min     0.000724  0.003736  0.005309  0.003648  0.010721  0.010272  0.003286   
max     0.997939  0.985886  0.994739  0.991139  0.978756  0.995943  0.994109   
var     0.084670  0.080833  0.076592  0.085082  0.078434  0.084377  0.070889   

          feat_7    feat_8    feat_9  ...   feat_20   feat_21   feat_22  \
mean    0.509505  0.527279  0.508659  ...  0.504695  0.476640  0.478189   
median  0.548298  0.540437  0.536755  ...  0.536256  0.497183  0.495235   
min     0.004605  0.007458  0.002316  ...  0.000827  0.013209  0.011660   
max     0.992959  0.998271  0.995032  ...  0.999651  0.989118  0.999271   
var     0.066931  0.078488  0.075348  ...  0.094052  0.083316  0.084250   

         feat_23   feat_24   feat_25   feat_26   feat_27   feat_28   feat_29  
mean    0.493988  0.493857  0.497066  0.488031  0.484862  0.454865  0.512115  
median  0.525425  0.516342  0.492070  0.521140  0.466882  0.433368  0.543300  
min     0.005152  0.000800  0.012059  0.001383  0.000461  0.001857  0.012810  
max     0.992832  0.997314  0.995497  0.991337  0.998554  0.980994  0.999962  
var     0.071903  0.088868  0.085205  0.085559  0.089171  0.072175  0.082522  

[5 rows x 30 columns]

In [9]:
from si.io.data_file import read_data_file

# read breast dataset from data file
breast_dataset = read_data_file('../datasets/breast_bin/breast-bin.data', sep=',', label=True)
breast_dataset.summary()

feat_0     feat_1     feat_2     feat_3     feat_4     feat_5  \
mean     4.417740   3.134478   3.207439   2.806867   3.216023   3.486409   
median   4.000000   1.000000   1.000000   1.000000   2.000000   1.000000   
min      1.000000   1.000000   1.000000   1.000000   1.000000   1.000000   
max     10.000000  10.000000  10.000000  10.000000  10.000000  10.000000   
var      7.917053   9.298082   8.819630   8.141527   4.896110  13.099601   

           feat_6     feat_7     feat_8  
mean     3.437768   2.866953   1.589413  
median   3.000000   1.000000   1.000000  
min      1.000000   1.000000   1.000000  
max     10.000000  10.000000  10.000000  
var      5.937114   9.311340   2.937284

In [10]:
breast_dataset.y

array([1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1.,
       1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0.,
       1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0.,
       0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0.,
       0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 0., 1., 0., 0.

In [11]:
print('Features', breast_dataset.features)
print('Label', breast_dataset.label)

Features ['feat_0', 'feat_1', 'feat_2', 'feat_3', 'feat_4', 'feat_5', 'feat_6', 'feat_7', 'feat_8']
Label y


In [12]:
# write the same fila with a different name
from si.io.data_file import write_data_file
write_data_file('../datasets/breast_bin/breast-bin_tabular.tsv', breast_dataset, sep='\t', label=True)

In [13]:
from si.io.csv_file import read_csv

# read iris dataset from data file
iris_dataset = read_csv('../datasets/iris/iris.csv', sep=',', features=True, label=True)
iris_dataset.summary()

sepal_length  sepal_width  petal_length  petal_width
mean        5.843333     3.054000      3.758667     1.198667
median      5.800000     3.000000      4.350000     1.300000
min         4.300000     2.000000      1.000000     0.100000
max         7.900000     4.400000      6.900000     2.500000
var         0.681122     0.186751      3.092425     0.578532

In [14]:
iris_dataset.get_classes()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [15]:
# write the same file with a different name
from si.io.csv_file import write_csv
write_csv('../datasets/iris/iris_tabular.tsv', iris_dataset, sep='\t', features=True, label=True)

In [16]:
# random dataset
from si.data.dataset import Dataset
random_dataset = Dataset.from_random(150, 30, 4)
random_dataset.get_classes()

array([0, 1, 2, 3])

In [17]:
# from dataframe
import numpy as np
import pandas as pd

df = pd.DataFrame(np.random.rand(150, 30))
df_dataset = Dataset.from_dataframe(df)
df_dataset.X

array([[0.04849695, 0.31174711, 0.53047036, ..., 0.86053998, 0.36092023,
        0.83430281],
       [0.194156  , 0.12932776, 0.36563077, ..., 0.39707471, 0.00386602,
        0.25693859],
       [0.21626118, 0.00494963, 0.55551151, ..., 0.99986214, 0.30627485,
        0.65444478],
       ...,
       [0.74288047, 0.31719079, 0.09263613, ..., 0.34119046, 0.69689828,
        0.57117672],
       [0.07080447, 0.95948622, 0.47044809, ..., 0.1804325 , 0.59580854,
        0.61092903],
       [0.28089423, 0.40581775, 0.82886292, ..., 0.64529437, 0.5173127 ,
        0.50470528]])

In [18]:
df_dataset.has_label()

False

In [28]:
df_w_nas = read_csv('../datasets/iris/iris_missing_data.csv', sep=',', features=True, label=True)
df_w_nas.X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, nan, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, nan],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, nan, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [nan, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, nan],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, nan],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [29]:
from copy import copy

df1 = copy(df_w_nas).dropna()
df1.X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3

In [32]:
df2 = copy(df_w_nas).fillna(0)
df2.X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 0. , 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0. ],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 0. , 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [0. , 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0. ],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0. ],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [33]:
df2.remove_by_index(0)
df2.X

array([[4.9, 3. , 1.4, 0.2],
       [4.7, 0. , 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0. ],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 0. , 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [0. , 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0. ],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0. ],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5. , 3