## SIB - P1

A Jupyter Notebook with examples of how to use the Dataset object.
18/09/2023

In [1]:
from si.data.dataset import Dataset
import numpy as np

# create a dataset
X = np.random.rand(150, 30)
y = np.random.randint(0, 2, 150)
dataset = Dataset(X, y)
dataset.shape()

(150, 30)

In [2]:
# get the X
dataset.X

array([[0.80182365, 0.64113488, 0.84614098, ..., 0.1974185 , 0.48823947,
        0.60515804],
       [0.11446785, 0.42871156, 0.38681656, ..., 0.54262138, 0.95005298,
        0.03324341],
       [0.7490716 , 0.2679309 , 0.79301099, ..., 0.8514416 , 0.47030137,
        0.66025425],
       ...,
       [0.33000589, 0.99302457, 0.18718585, ..., 0.90100379, 0.6469107 ,
        0.39255508],
       [0.699436  , 0.16665558, 0.84618154, ..., 0.48881593, 0.32887293,
        0.59563643],
       [0.19225852, 0.53298539, 0.40024606, ..., 0.9029513 , 0.13946034,
        0.80472977]])

In [3]:
#get the features names
dataset.features

['feat_0',
 'feat_1',
 'feat_2',
 'feat_3',
 'feat_4',
 'feat_5',
 'feat_6',
 'feat_7',
 'feat_8',
 'feat_9',
 'feat_10',
 'feat_11',
 'feat_12',
 'feat_13',
 'feat_14',
 'feat_15',
 'feat_16',
 'feat_17',
 'feat_18',
 'feat_19',
 'feat_20',
 'feat_21',
 'feat_22',
 'feat_23',
 'feat_24',
 'feat_25',
 'feat_26',
 'feat_27',
 'feat_28',
 'feat_29']

In [4]:
# has label?
dataset.has_label()

True

In [5]:
# print the label
dataset.y

array([0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0])

In [6]:
# get classes
dataset.get_classes()

array([0, 1])

In [7]:
# statistics summary
dataset.summary()

feat_0    feat_1    feat_2    feat_3    feat_4    feat_5    feat_6  \
mean    0.511740  0.538124  0.513318  0.489376  0.485406  0.520775  0.492468   
median  0.526549  0.530198  0.545863  0.504126  0.484300  0.545841  0.492076   
min     0.003316  0.001000  0.001950  0.002905  0.011057  0.000554  0.004232   
max     0.992733  0.998717  0.992570  0.996555  0.988860  0.999186  0.998293   
var     0.087077  0.086508  0.082163  0.085521  0.074018  0.085260  0.088788   

          feat_7    feat_8    feat_9  ...   feat_20   feat_21   feat_22  \
mean    0.527520  0.522368  0.476033  ...  0.544720  0.482406  0.534396   
median  0.534609  0.514701  0.472715  ...  0.562027  0.478725  0.548770   
min     0.015953  0.008558  0.001146  ...  0.004212  0.000575  0.003150   
max     0.995730  0.988180  0.990188  ...  0.993511  0.995512  0.994265   
var     0.088145  0.084098  0.089272  ...  0.084876  0.080458  0.087790   

         feat_23   feat_24   feat_25   feat_26   feat_27   feat_28   feat_29  
mean    0.494289  0.473856  0.515729  0.481647  0.465210  0.516526  0.508717  
median  0.507717  0.482148  0.559053  0.478616  0.449303  0.489996  0.518561  
min     0.000615  0.002833  0.016312  0.015125  0.000034  0.005493  0.013004  
max     0.996088  0.991793  0.990758  0.994653  0.989550  0.983990  0.983210  
var     0.081090  0.086907  0.083115  0.081015  0.084023  0.077617  0.082992  

[5 rows x 30 columns]

In [9]:
from si.io.data_file import read_data_file

# read breast dataset from data file
breast_dataset = read_data_file('../datasets/breast_bin/breast-bin.data', sep=',', label=True)
breast_dataset.summary()

feat_0     feat_1     feat_2     feat_3     feat_4     feat_5  \
mean     4.417740   3.134478   3.207439   2.806867   3.216023   3.486409   
median   4.000000   1.000000   1.000000   1.000000   2.000000   1.000000   
min      1.000000   1.000000   1.000000   1.000000   1.000000   1.000000   
max     10.000000  10.000000  10.000000  10.000000  10.000000  10.000000   
var      7.917053   9.298082   8.819630   8.141527   4.896110  13.099601   

           feat_6     feat_7     feat_8  
mean     3.437768   2.866953   1.589413  
median   3.000000   1.000000   1.000000  
min      1.000000   1.000000   1.000000  
max     10.000000  10.000000  10.000000  
var      5.937114   9.311340   2.937284

In [10]:
breast_dataset.y

array([1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1.,
       1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0.,
       1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0.,
       0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0.,
       0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 0., 1., 0., 0.

In [11]:
print('Features', breast_dataset.features)
print('Label', breast_dataset.label)

Features ['feat_0', 'feat_1', 'feat_2', 'feat_3', 'feat_4', 'feat_5', 'feat_6', 'feat_7', 'feat_8']
Label y


In [12]:
# write the same fila with a different name
from si.io.data_file import write_data_file
write_data_file('../datasets/breast_bin/breast-bin_tabular.tsv', breast_dataset, sep='\t', label=True)

In [13]:
from si.io.csv_file import read_csv

# read iris dataset from data file
iris_dataset = read_csv('../datasets/iris/iris.csv', sep=',', features=True, label=True)
iris_dataset.summary()

sepal_length  sepal_width  petal_length  petal_width
mean        5.843333     3.054000      3.758667     1.198667
median      5.800000     3.000000      4.350000     1.300000
min         4.300000     2.000000      1.000000     0.100000
max         7.900000     4.400000      6.900000     2.500000
var         0.681122     0.186751      3.092425     0.578532

In [14]:
iris_dataset.get_classes()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [15]:
# write the same file with a different name
from si.io.csv_file import write_csv
write_csv('../datasets/iris/iris_tabular.tsv', iris_dataset, sep='\t', features=True, label=True)

In [16]:
# random dataset
from si.data.dataset import Dataset
random_dataset = Dataset.from_random(150, 30, 4)
random_dataset.get_classes()

array([0, 1, 2, 3])

In [17]:
# from dataframe
import numpy as np
import pandas as pd

df = pd.DataFrame(np.random.rand(150, 30))
df_dataset = Dataset.from_dataframe(df)
df_dataset.X

array([[5.65490247e-01, 1.42116681e-01, 1.78831969e-01, ...,
        1.51886478e-01, 5.98699117e-01, 2.24093412e-02],
       [4.80373815e-01, 9.47437033e-01, 4.60260208e-01, ...,
        6.98362316e-02, 1.42123571e-01, 1.69508721e-01],
       [4.05842734e-05, 8.78147404e-01, 9.88638863e-01, ...,
        1.70170799e-01, 2.43136393e-01, 9.17116292e-03],
       ...,
       [8.19730438e-01, 7.72757419e-02, 9.29274936e-01, ...,
        4.02392750e-01, 5.65532913e-02, 6.92779184e-01],
       [4.12591273e-01, 5.78955754e-01, 6.72865100e-01, ...,
        2.46527961e-01, 5.74853478e-02, 5.80791660e-01],
       [1.41894699e-01, 1.15561158e-01, 9.97940769e-01, ...,
        5.95912294e-01, 3.38226855e-01, 2.91132291e-01]])

In [18]:
df_dataset.has_label()

False